Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # --- ns: Control Plane ---
  config.vm.define "ns" do |ns|
    ns.vm.hostname = "ns"
    ns.vm.network "private_network", ip: "192.168.56.119"
    # REMOVED ssh.host and ssh.port to allow Vagrant to provision the network first
    
    # Sync free5gc-helm folder
    ns.vm.synced_folder "../free5gc-helm", "/home/vagrant/free5gc-helm"
    
    ns.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end

# --- ns2: User Plane (UPF) ---
  config.vm.define "ns2" do |ns2|
    ns2.vm.hostname = "ns2"
    
    # Explicit routing fix to ensure internet works
    ns2.vm.network "private_network", 
      ip: "192.168.56.120", 
      netmask: "255.255.255.0"

    # Sync free5gc-helm folder
    ns2.vm.synced_folder "../free5gc-helm", "/home/vagrant/free5gc-helm"

    ns2.vm.provider "virtualbox" do |vb|
      #vb.gui = true       # Keep GUI on just in case
      vb.memory = "8192"  # Reduced to 8GB
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end

  # --- VM3: UE/RAN Simulator ---
  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", ip: "192.168.56.118"
    
    # Sync UERANSIM folder
    vm3.vm.synced_folder "../UERANSIM", "/home/vagrant/UERANSIM"
    
    vm3.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end
end
# Vagrant.configure("2") do |config|
#   # Use Ubuntu 20.04 (Focal) as the base image
#   config.vm.box = "ubuntu/focal64"
  
#   # Disable the default synced folder to prevent permission issues
#   config.vm.synced_folder ".", "/vagrant", disabled: true

#   # --- ns: Control Plane ---
#   config.vm.define "ns" do |ns|
#     ns.vm.hostname = "ns"
#     # This creates the Host-Only adapter automatically with the static IP
#     ns.vm.network "private_network", ip: "192.168.56.119"
#     ns.ssh.host = "192.168.56.119"
#     ns.ssh.port = 22
    
#     ns.vm.provider "virtualbox" do |vb|
#       vb.memory = "16000"
#       vb.cpus = 4
#       # Essential: Enable Promiscuous mode for 5G traffic
#       vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
#     end
#   end

#   # --- ns2: User Plane (UPF) ---
#   config.vm.define "ns2" do |ns2|
#     ns2.vm.hostname = "ns2"
#     ns2.vm.network "private_network", ip: "192.168.56.120"
#     ns2.ssh.host = "192.168.56.120"
#     ns2.ssh.port = 22
    
#     ns2.vm.provider "virtualbox" do |vb|
#       vb.memory = "16000"
#       vb.cpus = 4
#       vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
#     end
#   end

#   # --- VM3: UE/RAN Simulator ---
#   config.vm.define "vm3" do |vm3|
#     vm3.vm.hostname = "vm3"
#     vm3.vm.network "private_network", ip: "192.168.56.118"
#     vm3.ssh.host = "192.168.56.118"
#     vm3.ssh.port = 22
    
#     vm3.vm.provider "virtualbox" do |vb|
#       vb.memory = "8092"
#       vb.cpus = 2
#       vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
#     end
#   end
# end